### ISSUE TITLE
how to read double pulses on inputs of railduino

### ISSUE THREAD

**Issue by koraysels** [dusanmsk/railduino-udp#7]
hi, i have a railduino 1.3 with the udp firmware running for quite some time now. If functions great as an affordable relay board. But now that i have run out of inputs on loxone devices I started using the inputs of the railduino. Which work fine (altough with a noticable delay) but..

I cannot detect double clicks .. 
Is the railduino throtling udp messages or what is going on ? is there a way to still have this functionality?

thanks in advance!

**Comment by Rubeast** [comment]
Double click doesn't work with railduino. So that's normal behavior.

**Comment by koraysels** [comment]
maybe with a firmware update..? but then it would have to introduce a delay for the arduino to wait for a possible second click before sending a special double click message..

**Comment by dusanmsk** [comment]
Hi there. I am not maintaining this repo anymore because I dont own railduino anymore - I've built my own arduino-based io extension board. But basicaly my board and current Railduino has very similar codebase (Railduino author forked my repo back to his codebase and now it is a core part of an official Railduino firmware releases (or was for a some period of time - as I say - I am 3+ years out)) so I could say there is no technical issue handling doubleclicks with arduino and loxone using udp. You should ask original Railduino author to check/fix this problem, maybe relayduino firmware is not flushing/closing udp socket immediately after sending a packet - who knows...

**Comment by dusanmsk** [comment]
See here - https://github.com/PavSedl/railduino-udp

**Comment by PavSedl** [comment]
Hi there, as dusanmsk said correctly, there is no issue with handling double clicks with Railduino module. The shortest detectable pulse at dig. input is about 20ms when using LAN, 35ms when using RS485 (all with UDP packets).
Still I recommend to update your firmware to the latest version [HERE](https://sedtronic.eu/en/index.php?controller=attachment&id_attachment=5)
